env:
  browser: true
  es2021: true
extends:
- airbnb
- "plugin:react-hooks/recommended"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
rules: {
  "react/forbid-prop-types": [0, {}],
  "template-curly-spacing": "off",
  "no-use-before-define": ["error", { "variables": false, "functions": false }],
  "react/require-default-props": [0, {}]
}
